[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/_v/*"
  to = "https://vigil.intpub.workers.dev/_v/:splat"
  status = 200
